version: '3'

services:
  keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - 8080:8080
    expose:
      - '8080'
    environment:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'admin123'
      KEYCLOAK_IMPORT: '/realm/vuejs-keycloak-auth-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled'
    volumes:
      - ./keycloak-config:/realm/

  vuejs-keycloak-auth:
    build:
      context: .
      dockerfile: Dockerfile.develop
    ports:
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      - keycloak
    volumes:
      - .:/app:delegated
      - /app/node_modules
